#!/usr/bin/env bash

# 1. Format code
printf "\e[33;1m%s\e[0m\n" 'Running dart format'

result=$(dart format .)
result_lines=$(echo "$result" | wc -l)

if [ "$result_lines" -gt 1 ]; then
  echo "$result"
  printf "\e[31;1m%s\e[0m\n" 'Dart format applied changes, please recommit'
  exit 1
fi

echo "$result"
printf "\e[32;1m%s\e[0m\n" 'Finished running dart format'

# 2. Analyze code (flutter analyze)
printf "\e[33;1m%s\e[0m\n" 'Running flutter analyze'
result=$(flutter analyze)

if [ $? -ne 0 ]; then
  echo -e "$result \n"
  printf "\e[31;1m%s\e[0m\n" 'Flutter analyze found the above issues, please fix them before pushing'
  exit 1
fi

echo "$result"
printf "\e[32;1m%s\e[0m\n" 'Finished running Flutter analyze with 0 issues'
