#!/usr/bin/env bash

# 1. Ensure there are not uncommited files
if [[ `git status --porcelain` ]]; then
  printf "\e[31;1m%s\e[0m\n" 'This script needs to run against committed code only. Please commit or stash you changes.'
  exit 1
fi

# 2. Run flutter test
printf "\e[33;1m%s\e[0m\n" 'Running flutter test'
result=$(flutter test)

if [ $? -ne 0 ]; then
  echo -e "$result \n"
  printf "\e[31;1m%s\e[0m\n" '1 or more test(s) failed'
  exit 1
fi

echo "$result"
printf "\e[32;1m%s\e[0m\n" 'Finished running flutter test'
