name: saloonprived_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  country_picker: ^2.0.26
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  smart_select: ^4.2.1
  url_strategy: ^0.3.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/i18n/
    - assets/images/
